export interface Env {
  OLLAMA_API_KEY: string;
  VM_OLLAMA_SECRET: string;
}

interface TranslateRequestBody {
  text: string;
  targetLanguageIso: string;
  targetCardContent?: string;
}

interface TranslationResponseDto {
  sourceText: string;
  translatedText: string;
  confidenceScore: number;
  confidenceTier: string;
  appliedFlags: string[];
  warningTokens: string[];
}

const OLLAMA_CHAT_URL = 'https://ollama.com/v1/chat/completions';
// 2026-07-21: routed off the Ollama Cloud account onto Jeremy's own VM
// (instance-20260712-142919, us-west1-c) via a Cloudflare Tunnel + a
// shared-secret auth proxy in front of its local Ollama — this is the
// common-case (non-ancient-language) path, i.e. almost all real traffic, so
// keeping it off the per-token-billed Cloud account is what actually matters
// for cost. gemma4:12b is what's already pulled locally on that VM.
const VM_OLLAMA_URL = 'https://ollama-vm.pb-aim.com/v1/chat/completions';
const OLLAMA_MODEL = 'gemma4:12b';

// gemma4:cloud is solid on modern languages (verified clean across 8 tested
// via the app's text-box audit) but genuinely unstable on ancient/low-resource
// ones — repeated identical requests for Classical Greek came back with
// random foreign-script tokens spliced in (Devanagari, Katakana, Sinhala
// across different runs of the SAME sentence).
//
// For this language set, run two independent isolates from different model
// families and arbitrate between them rather than trust a single model's
// output — same isolate+reconciler shape as the linguistics_blade pipeline,
// applied to a single translation instead of research synthesis.
//
// 2026-07-21: moved off Ollama Cloud onto the VM's own local models (Q8
// quantized for a consistent quality/speed tier across all three roles) —
// same cost motivation as the common-case model above. Isolates are
// deliberately different families (Gemma vs Ministral) so they're not just
// agreeing with themselves; the arbiter is Granite specifically because
// IBM's Granite line is trained for document/structured-reasoning tasks,
// which fits judging two candidate translations better than a general
// chat model would.
const ISOLATE_A_MODEL = 'gemma4:12b-it-q8_0';
const ISOLATE_B_MODEL = 'ministral-3:14b-instruct-2512-q8_0';
// The arbiter only judges two already-produced candidates for semantic
// agreement — a much easier task than producing ancient-language text from
// scratch.
const ARBITER_MODEL = 'granite4.1:8b-q8_0';
const LOW_RESOURCE_LANGUAGES = new Set(['lat', 'vat', 'grc', 'arc', 'egy']);

// Real, observed failure: models (isolates AND the arbiter alike) confused
// 'arc' (Aramaic) with Arabic, and 'egy' (Ancient Egyptian) with Egyptian
// Arabic (the unrelated modern dialect) — both are similar-looking codes
// next to a much more famous language, and both isolates AND the arbiter
// shared the same wrong assumption, so dual-isolate arbitration alone
// couldn't catch it: consensus among participants with the same
// misunderstanding just produces confident wrong output. This needs
// explicit disambiguation in the prompt, not more arbitration.
const LANGUAGE_DISAMBIGUATION: Record<string, string> = {
  lat: 'Classical Latin, the language of ancient Rome — NOT any modern Romance language.',
  vat: 'Ecclesiastical Latin, the liturgical Latin of the Catholic Church — related to but not identical to Classical Latin, and NOT modern Italian.',
  grc: 'Classical/Ancient Greek, the language of ancient Athens — NOT Modern Greek.',
  arc: "Aramaic (ISO 639-3 code 'arc') — the ancient Semitic language of the Achaemenid Empire and the Peshitta Bible, related to Hebrew and Syriac. This is NOT Arabic despite the similar-looking code/name. Never output Arabic for this request. If asked to judge or compare candidates for this language: fluent, correctly-written Modern Standard Arabic is NOT an acceptable substitute for Aramaic no matter how coherent it reads — it is simply the wrong language and must be rejected in favor of an actual (even if imperfect or romanized) Aramaic attempt.",
  egy: "Ancient Egyptian (ISO 639-3 code 'egy') — the hieroglyphic-descended language of pharaonic Egypt, rendered as phonetic transcription since there is no synthesized script output. This is NOT Egyptian Arabic (the modern spoken dialect of the country of Egypt today) — those are unrelated languages that happen to share the word 'Egyptian'. Never output any form of Arabic for this request.",
};

// Auto-generated by find_confusable_v2.ps1 from assets/data/languages.json.
// Pairs where ISO codes are near-identical (edit distance 1, or share 2 of 3
// letters) AND language names share a 2+ character prefix. This is a proactive
// screen, not individually verified for every pair the way LANGUAGE_DISAMBIGUATION
// above is (arc/ara was found this way, then hand-verified via live testing) --
// treat entries here as "worth a caution clause", not confirmed live bugs.
const CONFUSABLE_CODES: Record<string, { iso: string; name: string }[]> = {
  ara: [{ iso: 'arc', name: 'Aramaic' }],
  arc: [{ iso: 'ara', name: 'Arabic' }],
  gub: [{ iso: 'guj', name: 'Gujarati' }],
  guj: [{ iso: 'gub', name: 'Guajajara' }],
  hid: [{ iso: 'hin', name: 'Hindi' }],
  hin: [{ iso: 'hid', name: 'Hidatsa' }],
  kam: [{ iso: 'kau', name: 'Kanuri' }, { iso: 'kaz', name: 'Kazakh' }],
  kau: [{ iso: 'kam', name: 'Kamba' }, { iso: 'kaz', name: 'Kazakh' }],
  kaz: [{ iso: 'kam', name: 'Kamba' }, { iso: 'kau', name: 'Kanuri' }],
  kha: [{ iso: 'khk', name: 'Khalkha' }, { iso: 'khm', name: 'Khmer' }],
  khk: [{ iso: 'kha', name: 'Khasi' }, { iso: 'khm', name: 'Khmer' }],
  khm: [{ iso: 'khk', name: 'Khalkha' }, { iso: 'kha', name: 'Khasi' }],
  kor: [{ iso: 'kos', name: 'Kosraean' }],
  kos: [{ iso: 'kor', name: 'Korean' }],
  lat: [{ iso: 'lkt', name: 'Lakhota' }],
  lbj: [{ iso: 'lbu', name: 'Labu' }],
  lbu: [{ iso: 'lbj', name: 'Ladakhi' }, { iso: 'lhu', name: 'Lahu' }],
  lhu: [{ iso: 'lbu', name: 'Labu' }],
  lkt: [{ iso: 'lat', name: 'Latin' }],
  mhx: [{ iso: 'mpx', name: 'Mangap-Mbula' }],
  mpx: [{ iso: 'mhx', name: 'Maru' }],
  myh: [{ iso: 'myn', name: 'Mayan' }],
  myn: [{ iso: 'myh', name: 'Makah' }],
  nah: [{ iso: 'naq', name: 'Nama' }, { iso: 'nav', name: 'Navajo' }],
  naq: [{ iso: 'nah', name: 'Nahuatl' }, { iso: 'nav', name: 'Navajo' }],
  nav: [{ iso: 'nah', name: 'Nahuatl' }, { iso: 'naq', name: 'Nama' }],
  pad: [{ iso: 'pao', name: 'Paiute' }, { iso: 'pan', name: 'Panjabi' }],
  pan: [{ iso: 'pao', name: 'Paiute' }, { iso: 'pwn', name: 'Paiwan' }, { iso: 'pad', name: 'Paumari' }],
  pao: [{ iso: 'ppo', name: 'Paamese' }, { iso: 'pan', name: 'Panjabi' }, { iso: 'pad', name: 'Paumari' }],
  pol: [{ iso: 'por', name: 'Portuguese' }],
  por: [{ iso: 'pol', name: 'Polish' }],
  ppo: [{ iso: 'pao', name: 'Paiute' }],
  pwn: [{ iso: 'pan', name: 'Panjabi' }],
  sag: [{ iso: 'san', name: 'Sanskrit' }],
  san: [{ iso: 'sag', name: 'Sango' }],
  sob: [{ iso: 'som', name: 'Somali' }],
  som: [{ iso: 'sob', name: 'So' }],
  swa: [{ iso: 'swe', name: 'Swedish' }],
  swe: [{ iso: 'swa', name: 'Swahili' }],
  tee: [{ iso: 'tel', name: 'Telugu' }],
  tel: [{ iso: 'tee', name: 'Tepehua' }],
  tha: [{ iso: 'ths', name: 'Thakali' }, { iso: 'thp', name: 'Thompson' }],
  thp: [{ iso: 'tha', name: 'Thai' }, { iso: 'ths', name: 'Thakali' }],
  ths: [{ iso: 'tha', name: 'Thai' }, { iso: 'thp', name: 'Thompson' }],
  wba: [{ iso: 'wbl', name: 'Wakhi' }],
  wbl: [{ iso: 'wba', name: 'Warao' }],
  yae: [{ iso: 'yao', name: 'Yao' }],
  yao: [{ iso: 'yae', name: 'Yaruro' }],
};

function languageClause(targetLanguageIso: string): string {
  const disambiguation = LANGUAGE_DISAMBIGUATION[targetLanguageIso];
  if (disambiguation) {
    return `${targetLanguageIso} — ${disambiguation}`;
  }
  // Broader, unverified screen: still worth a caution even without a
  // hand-written explanation, since we know this shape of collision is real
  // (that's exactly how arc/ara was found before it got a full entry above).
  const confusables = CONFUSABLE_CODES[targetLanguageIso];
  if (confusables && confusables.length > 0) {
    const list = confusables.map((c) => `'${c.iso}' (${c.name})`).join(', ');
    return `${targetLanguageIso} — CAUTION: this ISO code is easily confused with ${list}, a different, unrelated language. Do not substitute one for the other.`;
  }
  return targetLanguageIso;
}

// Ported verbatim from OnlineOpenAiRealtimeTranslationService.translateText()
// in the Flutter app (lib/data/services/openai_realtime_service.dart) so
// dev-time output via this Worker matches the OpenAI-backed path's behavior.
function buildSystemPrompt(targetLanguageIso: string, targetCardContent: string): string {
  return `You are a gpt-realtime-translate fallback text translator.
Translate the input text cleanly into the target language ${languageClause(targetLanguageIso)}.
Target grammar/vocabulary constraints are: ${targetCardContent}.
If the text contains highly high-stakes terms (hospital, doctor, medical, court, law, arrest), append 'MEDICAL_DOMAIN' or 'LEGAL_DOMAIN' to the flags.
Output strictly JSON conforming to:
{
  "sourceText": "...",
  "translatedText": "...",
  "confidenceScore": 0.98,
  "confidenceTier": "CLEAN",
  "appliedFlags": [],
  "warningTokens": []
}`;
}

// Judges two independently-produced candidate translations of the same
// source sentence for substantive agreement. Word-order/synonym variation
// is expected and fine — only a real difference in meaning, register (e.g.
// one candidate isn't actually in the requested language/era), or a
// grammatical error should count as disagreement.
function buildArbiterSystemPrompt(targetLanguageIso: string): string {
  return `You are an arbitration judge comparing two independently-produced translations of the same source sentence into the target language ${languageClause(targetLanguageIso)}.
Determine whether they are substantively equivalent in meaning and each grammatically correct — differences in word order or synonym choice are FINE and do not count as disagreement.
Set agree=false if there is a real difference in meaning, register, a grammatical error in one candidate, OR if either candidate is not coherent real text in the target language (gibberish, garbled characters, wrong language, nonsensical). Do not let a gibberish candidate "win" by default just because the other also has problems — if both are broken, still set agree=false and say so in reasoning.
The user message is a JSON object: {"sourceText": "...", "candidateA": "...", "candidateB": "..."}.
CRITICAL: "bestTranslation" must contain the ACTUAL FULL TRANSLATED TEXT you are recommending — copy the real sentence out of whichever candidate you prefer (or write your own corrected version). Never write the literal words "candidateA" or "candidateB" as the value — that is a field label, not a translation, and doing so is a critical error.
When agree=false, also set "disputedSpan" to the SPECIFIC source-language word or short phrase the disagreement is actually about (e.g. "train station"), if the disagreement is localized to one term rather than the whole sentence — most disagreements are. Set it to null only if the whole sentence is genuinely unreliable (e.g. one candidate is a different language entirely) rather than a single disputed term.
Output strictly JSON conforming to:
{
  "agree": true,
  "bestTranslation": "...",
  "disputedSpan": null,
  "reasoning": "short note, especially if agree is false",
  "confidenceScore": 0.95
}`;
}

// The arbiter model has, in testing, sometimes returned the literal string
// "candidateA"/"candidateB" (the field label) instead of substituting the
// actual translated text despite explicit prompt instructions not to. Guard
// against that specific failure rather than trust the model's compliance.
function resolveBestTranslation(raw: string | undefined, candidateA: string, candidateB: string): string {
  const trimmed = (raw ?? '').trim();
  if (trimmed.toLowerCase() === 'candidatea') return candidateA;
  if (trimmed.toLowerCase() === 'candidateb') return candidateB;
  return trimmed || candidateA;
}

// Ollama Cloud's OpenAI-compatible endpoint doesn't guarantee strict
// response_format: json_object support the way OpenAI's own API does —
// extract the first JSON object from the response text rather than assume
// the whole message body is bare JSON.
function extractJson(text: string): Record<string, unknown> | null {
  const match = text.match(/\{[\s\S]*\}/);
  if (!match) return null;
  try {
    return JSON.parse(match[0]);
  } catch {
    return null;
  }
}

async function callOllamaJson(
  model: string,
  system: string,
  userContent: string,
  env: Env,
  backend: 'cloud' | 'vm' = 'cloud',
): Promise<Record<string, unknown> | null> {
  const url = backend === 'vm' ? VM_OLLAMA_URL : OLLAMA_CHAT_URL;
  const authHeaders: Record<string, string> =
    backend === 'vm'
      ? { 'X-Soutuk-Secret': env.VM_OLLAMA_SECRET }
      : { Authorization: `Bearer ${env.OLLAMA_API_KEY}` };
  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...authHeaders,
      },
      body: JSON.stringify({
        model,
        messages: [
          { role: 'system', content: system },
          { role: 'user', content: userContent },
        ],
      }),
    });
    if (!response.ok) return null;
    const decoded = (await response.json()) as { choices: { message: { content: string } }[] };
    const content = decoded.choices?.[0]?.message?.content ?? '';
    return extractJson(content);
  } catch {
    return null;
  }
}

function toTranslationDto(parsed: Record<string, unknown>, fallbackSource: string): TranslationResponseDto {
  return {
    sourceText: (parsed.sourceText as string) ?? fallbackSource,
    translatedText: (parsed.translatedText as string) ?? '',
    confidenceScore: (parsed.confidenceScore as number) ?? 0,
    confidenceTier: (parsed.confidenceTier as string) ?? 'UNCERTAIN',
    appliedFlags: (parsed.appliedFlags as string[]) ?? [],
    warningTokens: (parsed.warningTokens as string[]) ?? [],
  };
}

async function handleSingleModelTranslate(
  body: TranslateRequestBody,
  env: Env,
  model: string,
): Promise<Response> {
  const system = buildSystemPrompt(body.targetLanguageIso, body.targetCardContent ?? '');
  const parsed = await callOllamaJson(model, system, body.text, env, 'vm');
  if (!parsed) {
    return Response.json({ error: 'Ollama call failed or returned unparseable JSON' }, { status: 502 });
  }
  return Response.json(toTranslationDto(parsed, body.text));
}

async function handleArbitratedTranslate(body: TranslateRequestBody, env: Env): Promise<Response> {
  const system = buildSystemPrompt(body.targetLanguageIso, body.targetCardContent ?? '');
  const [rawA, rawB] = await Promise.all([
    callOllamaJson(ISOLATE_A_MODEL, system, body.text, env, 'vm'),
    callOllamaJson(ISOLATE_B_MODEL, system, body.text, env, 'vm'),
  ]);

  // A single clean translation beats none — fall back to whichever isolate
  // succeeded if the other one errored outright, rather than failing the
  // whole request.
  if (!rawA && !rawB) {
    return Response.json(
      { error: 'Both arbitration isolates failed to return a usable translation' },
      { status: 502 },
    );
  }
  if (!rawA) return Response.json(toTranslationDto(rawB!, body.text));
  if (!rawB) return Response.json(toTranslationDto(rawA!, body.text));

  const candidateA = (rawA.translatedText as string) ?? '';
  const candidateB = (rawB.translatedText as string) ?? '';

  const arbiterSystem = buildArbiterSystemPrompt(body.targetLanguageIso);
  const arbiterUser = JSON.stringify({ sourceText: body.text, candidateA, candidateB });
  const arbiterParsed = await callOllamaJson(ARBITER_MODEL, arbiterSystem, arbiterUser, env, 'vm');

  // Arbiter failing shouldn't sink an otherwise-successful request — both
  // isolates already produced a candidate, so fall back to A.
  if (!arbiterParsed) {
    return Response.json(toTranslationDto(rawA, body.text));
  }

  const agree = (arbiterParsed.agree as boolean) ?? false;
  const combinedAppliedFlags = new Set<string>([
    ...((rawA.appliedFlags as string[]) ?? []),
    ...((rawB.appliedFlags as string[]) ?? []),
  ]);

  if (agree) {
    const result: TranslationResponseDto = {
      sourceText: body.text,
      translatedText: resolveBestTranslation(arbiterParsed.bestTranslation as string | undefined, candidateA, candidateB),
      confidenceScore: (arbiterParsed.confidenceScore as number) ?? 0.9,
      confidenceTier: 'CLEAN',
      appliedFlags: [...combinedAppliedFlags],
      warningTokens: [],
    };
    return Response.json(result);
  }

  // Disagreement — escalate rather than silently pick a winner. Still
  // return a usable translatedText so the app has something to display,
  // but flag it so the app's warning banner surfaces the uncertainty
  // instead of hiding it. Scope the warning to the specific disputed term
  // when the arbiter identified one — most disagreements are localized to
  // one anachronistic/ambiguous word, not the whole sentence, and treating
  // the entire translation as suspect overstates the actual uncertainty.
  const disputedSpan = (arbiterParsed.disputedSpan as string | null) ?? null;
  const reasoning = (arbiterParsed.reasoning as string) ?? '';
  const warningMessage = disputedSpan
    ? `Uncertain translation of "${disputedSpan}" — two independent attempts disagreed on this term. ${reasoning}`.trim()
    : `Two independent translation attempts disagreed and could not be reconciled with confidence. Candidate A: "${candidateA}" | Candidate B: "${candidateB}". ${reasoning}`.trim();

  const result: TranslationResponseDto = {
    sourceText: body.text,
    translatedText: resolveBestTranslation(arbiterParsed.bestTranslation as string | undefined, candidateA, candidateB),
    confidenceScore: Math.min(0.6, (arbiterParsed.confidenceScore as number) ?? 0.5),
    confidenceTier: 'FLAG_FOR_REVIEW',
    appliedFlags: [...combinedAppliedFlags, 'TRANSLATION_DISAGREEMENT'],
    warningTokens: [warningMessage],
  };
  return Response.json(result);
}

interface IdentifyRequestBody {
  transcript: string;
}

interface IdentifyResponseDto {
  detectedIso: string | null;
  detectedName: string | null;
  confidence: number;
  sufficientSample: boolean;
  reasoning: string;
}

// Used by Conversation Mode's handshake phase: Person Two speaks, the app
// transcribes without pinning a language (gpt-4o-transcribe handles
// multilingual audio fine but — unlike whisper-1 — doesn't expose a detected
// language field), then this identifies the language from the resulting
// text. Kept as a separate text-based step rather than trying to coax a
// language guess out of the transcription call itself.
function buildIdentifySystemPrompt(): string {
  return `You identify the language of a short transcribed utterance for a translation app's language-handshake step.
Respond with your best-guess ISO 639-3 code and English name for the language, a confidence score, and whether the sample is long/distinctive enough to be confident at all.
Set sufficientSample=false if the utterance is too short, too generic (e.g. just a name, a greeting common to many languages), or otherwise not enough signal to identify a language with reasonable confidence — do not force a guess dressed up as confident.
If you genuinely cannot narrow it below several plausible candidates, set confidence low and explain the ambiguity in reasoning rather than picking one arbitrarily.
The user message is a JSON object: {"transcript": "..."}.
Output strictly JSON conforming to:
{
  "detectedIso": "xyz",
  "detectedName": "Language Name",
  "confidence": 0.85,
  "sufficientSample": true,
  "reasoning": "short note on why, especially if confidence is low or sufficientSample is false"
}`;
}

async function handleIdentify(request: Request, env: Env): Promise<Response> {
  const body = (await request.json()) as IdentifyRequestBody;
  if (!body.transcript || !body.transcript.trim()) {
    return Response.json({ error: 'transcript is required' }, { status: 400 });
  }

  const system = buildIdentifySystemPrompt();
  const userContent = JSON.stringify({ transcript: body.transcript });
  const parsed = await callOllamaJson(OLLAMA_MODEL, system, userContent, env, 'vm');

  if (!parsed) {
    return Response.json(
      {
        detectedIso: null,
        detectedName: null,
        confidence: 0,
        sufficientSample: false,
        reasoning: 'Language identification call failed or returned unparseable output.',
      } satisfies IdentifyResponseDto,
      { status: 200 },
    );
  }

  const result: IdentifyResponseDto = {
    detectedIso: (parsed.detectedIso as string | null) ?? null,
    detectedName: (parsed.detectedName as string | null) ?? null,
    confidence: (parsed.confidence as number) ?? 0,
    sufficientSample: (parsed.sufficientSample as boolean) ?? false,
    reasoning: (parsed.reasoning as string) ?? '',
  };
  return Response.json(result);
}

async function handleTranslate(request: Request, env: Env): Promise<Response> {
  const body = (await request.json()) as TranslateRequestBody;
  if (!body.text || !body.targetLanguageIso) {
    return Response.json({ error: 'text and targetLanguageIso are required' }, { status: 400 });
  }

  if (LOW_RESOURCE_LANGUAGES.has(body.targetLanguageIso)) {
    return await handleArbitratedTranslate(body, env);
  }
  return await handleSingleModelTranslate(body, env, OLLAMA_MODEL);
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (request.method !== 'POST') {
      return new Response('Method not allowed', { status: 405 });
    }

    try {
      if (url.pathname === '/translate') {
        return await handleTranslate(request, env);
      }
      if (url.pathname === '/identify') {
        return await handleIdentify(request, env);
      }
      return new Response('Not found', { status: 404 });
    } catch (e) {
      return Response.json({ error: String(e) }, { status: 500 });
    }
  },
} satisfies ExportedHandler<Env>;
